//! Backend-agnostic inference engine loop.
//!
//! This crate depends only on the plan and seam contracts. It does not know
//! about backend runtimes, device buffers, or model implementation details.

use std::collections::{BTreeMap, VecDeque};

use anyhow::{Result, bail};
use infer_plan::{
    DecodeRow, FinishReason, ForwardMode, ForwardPlan, PrefillRow, SlotToken, StepOutput,
};
use infer_seam::{BackendExecutor, KvPool, PollResult};

const STOP_TOKEN_ID: u32 = 0;

/// Stable handle returned to callers when a request is submitted.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RequestHandle(u64);

impl RequestHandle {
    /// Return the numeric id backing this handle.
    #[must_use]
    pub fn id(self) -> u64 {
        self.0
    }
}

/// Completed request state retained after its slot has been freed.
#[derive(Debug, Clone)]
pub struct CompletedRequest {
    /// Request handle.
    pub handle: RequestHandle,
    /// Prompt tokens submitted by the caller.
    pub prompt_tokens: Vec<u32>,
    /// Tokens generated by executor steps.
    pub generated_tokens: Vec<u32>,
    /// Final finish reason.
    pub finish: Option<FinishReason>,
}

#[derive(Debug, Clone)]
struct RequestState {
    handle: RequestHandle,
    prompt_tokens: Vec<u32>,
    generated_tokens: Vec<u32>,
    max_tokens: usize,
    prefilled: bool,
    done: bool,
    finish: Option<FinishReason>,
}

impl RequestState {
    fn new(handle: RequestHandle, prompt_tokens: Vec<u32>, max_tokens: usize) -> Self {
        Self {
            handle,
            prompt_tokens,
            generated_tokens: Vec::new(),
            max_tokens,
            prefilled: false,
            done: false,
            finish: None,
        }
    }

    fn complete_immediately(mut self, finish: FinishReason) -> Self {
        self.done = true;
        self.finish = Some(finish);
        self
    }
}

impl From<RequestState> for CompletedRequest {
    fn from(request: RequestState) -> Self {
        Self {
            handle: request.handle,
            prompt_tokens: request.prompt_tokens,
            generated_tokens: request.generated_tokens,
            finish: request.finish,
        }
    }
}

/// Minimal backend-agnostic engine loop.
///
/// R1a intentionally keeps scheduling simple: first-come admission into empty
/// slots, full-prompt prefill, then one-token decode until completion.
pub struct Engine<E: BackendExecutor, K: KvPool> {
    executor: E,
    kv: K,
    max_slots: usize,
    next_request_id: u64,
    active: BTreeMap<usize, RequestState>,
    waiting: VecDeque<RequestState>,
    completed: BTreeMap<RequestHandle, CompletedRequest>,
    inflight: Option<E::Inflight>,
}

impl<E: BackendExecutor, K: KvPool> Engine<E, K> {
    /// Create an engine with a fixed number of logical slots.
    #[must_use]
    pub fn new(executor: E, kv: K, max_slots: usize) -> Self {
        Self {
            executor,
            kv,
            max_slots,
            next_request_id: 0,
            active: BTreeMap::new(),
            waiting: VecDeque::new(),
            completed: BTreeMap::new(),
            inflight: None,
        }
    }

    /// Submit a request into the waiting queue.
    pub fn submit_request(&mut self, prompt_tokens: Vec<u32>, max_tokens: usize) -> RequestHandle {
        let handle = RequestHandle(self.next_request_id);
        self.next_request_id = self.next_request_id.saturating_add(1);
        self.waiting
            .push_back(RequestState::new(handle, prompt_tokens, max_tokens));
        handle
    }

    /// Run one scheduler tick.
    ///
    /// Overlap ordering: the previous executor step is polled first; if it is
    /// still running, this tick exits and keeps the in-flight handle. Once the
    /// previous step completes, the CPU side admits requests and builds plan
    /// N+1 while the executor had already run plan N behind the seam.
    pub fn step(&mut self) -> Result<()> {
        if let Some(inflight) = self.inflight.take() {
            match self.executor.poll(inflight)? {
                PollResult::Ready(output) => self.apply_output(output),
                PollResult::NotReady(inflight) => {
                    self.inflight = Some(inflight);
                    return Ok(());
                }
            }
        }

        self.admit_waiting()?;
        let plan = self.build_forward_plan();
        if plan.is_idle() {
            return Ok(());
        }

        self.allocate_for_plan(&plan)?;
        log::trace!("infer-core submit plan: mode={:?}", plan.mode);
        self.inflight = Some(self.executor.submit(&plan, &mut self.kv)?);
        Ok(())
    }

    /// Run scheduler ticks until there is no waiting, active, or in-flight work.
    pub fn run_to_idle(&mut self) -> Result<()> {
        while !self.is_idle() {
            self.step()?;
        }
        Ok(())
    }

    /// Return whether the engine has no queued, active, or in-flight work.
    #[must_use]
    pub fn is_idle(&self) -> bool {
        self.waiting.is_empty() && self.active.is_empty() && self.inflight.is_none()
    }

    /// Return whether an executor step is currently in flight.
    #[must_use]
    pub fn has_inflight(&self) -> bool {
        self.inflight.is_some()
    }

    /// Return the number of active slots.
    #[must_use]
    pub fn active_count(&self) -> usize {
        self.active.len()
    }

    /// Return the number of waiting requests.
    #[must_use]
    pub fn waiting_count(&self) -> usize {
        self.waiting.len()
    }

    /// Return a completed request by handle.
    #[must_use]
    pub fn completed(&self, handle: RequestHandle) -> Option<&CompletedRequest> {
        self.completed.get(&handle)
    }

    fn apply_output(&mut self, output: StepOutput) {
        let mut finished_slots = Vec::new();

        for token in output.tokens {
            let Some(request) = self.active.get_mut(&token.slot) else {
                continue;
            };

            request.prefilled = true;
            request.generated_tokens.push(token.token);

            if let Some(finish) = finish_reason_for(request, &token) {
                request.done = true;
                request.finish = Some(finish);
                finished_slots.push(token.slot);
            }
        }

        for slot in finished_slots {
            if let Some(request) = self.active.remove(&slot) {
                self.kv.free_slot(slot);
                self.completed.insert(request.handle, request.into());
            }
        }
    }

    fn admit_waiting(&mut self) -> Result<()> {
        if self.max_slots == 0 && !self.waiting.is_empty() {
            bail!("infer-core engine has waiting requests but zero slots");
        }

        for slot in 0..self.max_slots {
            if self.waiting.is_empty() {
                break;
            }
            if self.active.contains_key(&slot) {
                continue;
            }

            let Some(request) = self.waiting.pop_front() else {
                break;
            };
            if request.max_tokens == 0 {
                let completed = request.complete_immediately(FinishReason::Length);
                self.completed.insert(completed.handle, completed.into());
            } else {
                self.active.insert(slot, request);
            }
        }
        Ok(())
    }

    fn build_forward_plan(&self) -> ForwardPlan {
        let mut prefill_rows = Vec::new();
        let mut decode_rows = Vec::new();

        for (&slot, request) in &self.active {
            if request.done {
                continue;
            }

            if !request.prefilled {
                prefill_rows.push(PrefillRow {
                    slot,
                    tokens: request.prompt_tokens.clone(),
                    start_pos: 0,
                    total_tokens: request.prompt_tokens.len(),
                });
                continue;
            }

            let Some(&last_token) = request.generated_tokens.last() else {
                continue;
            };
            decode_rows.push(DecodeRow {
                slot,
                last_token,
                kv_seq_len: self.kv.seq_len(slot),
            });
        }

        let mode = match (prefill_rows.is_empty(), decode_rows.is_empty()) {
            (true, true) => ForwardMode::Idle,
            (false, true) => ForwardMode::Prefill,
            (true, false) => ForwardMode::Decode,
            (false, false) => ForwardMode::Mixed,
        };

        ForwardPlan {
            mode,
            decode_rows,
            prefill_rows,
            microbatch: None,
            spec: None,
        }
    }

    fn allocate_for_plan(&mut self, plan: &ForwardPlan) -> Result<()> {
        for row in &plan.prefill_rows {
            self.kv.alloc(row.slot, row.tokens.len())?;
        }
        for row in &plan.decode_rows {
            self.kv.alloc(row.slot, 1)?;
        }
        Ok(())
    }
}

fn finish_reason_for(request: &RequestState, token: &SlotToken) -> Option<FinishReason> {
    token.finish.clone().or_else(|| {
        if token.token == STOP_TOKEN_ID {
            Some(FinishReason::Stop)
        } else if request.generated_tokens.len() >= request.max_tokens {
            Some(FinishReason::Length)
        } else {
            None
        }
    })
}

#[cfg(test)]
mod testing {
    use std::collections::HashSet;

    use anyhow::{Result, bail};
    use infer_plan::{SlotToken, StepOutput};
    use infer_seam::{BackendExecutor, KvPool, PollResult};

    use super::ForwardPlan;

    #[derive(Debug, Clone)]
    pub(super) struct MockKvPool {
        page_size: usize,
        seq_lens: Vec<usize>,
        pages: Vec<Vec<u32>>,
        slot_epochs: Vec<u64>,
        next_page: u32,
        retained_pages: HashSet<u32>,
    }

    impl MockKvPool {
        pub(super) fn new(num_slots: usize) -> Self {
            Self {
                page_size: 16,
                seq_lens: vec![0; num_slots],
                pages: vec![Vec::new(); num_slots],
                slot_epochs: vec![0; num_slots],
                next_page: 1,
                retained_pages: HashSet::new(),
            }
        }

        fn ensure_slot(&self, slot: usize) -> Result<()> {
            if slot >= self.seq_lens.len() {
                bail!("slot {slot} out of range");
            }
            Ok(())
        }

        fn alloc_pages(&mut self, count: usize) -> Vec<u32> {
            let mut pages = Vec::with_capacity(count);
            for _ in 0..count {
                pages.push(self.next_page);
                self.next_page = self.next_page.saturating_add(1);
            }
            pages
        }
    }

    impl KvPool for MockKvPool {
        fn is_active(&self) -> bool {
            true
        }

        fn page_size(&self) -> usize {
            self.page_size
        }

        fn free_pages(&self) -> usize {
            usize::MAX / self.page_size
        }

        fn free_tokens(&self) -> usize {
            usize::MAX / 2
        }

        fn seq_len(&self, slot: usize) -> usize {
            self.seq_lens[slot]
        }

        fn page_indices(&self, slot: usize) -> &[u32] {
            &self.pages[slot]
        }

        fn page_indices_for_token_range(&self, slot: usize, start: usize, len: usize) -> &[u32] {
            let start_page = start / self.page_size;
            let end_page = (start + len).div_ceil(self.page_size);
            &self.pages[slot][start_page..end_page]
        }

        fn slot_epoch(&self, slot: usize) -> u64 {
            self.slot_epochs[slot]
        }

        fn append_pages_needed(&self, slot: usize, tokens: usize) -> usize {
            if tokens == 0 {
                return 0;
            }
            let tail = self.seq_lens[slot] % self.page_size;
            let available = if tail == 0 { 0 } else { self.page_size - tail };
            tokens.saturating_sub(available).div_ceil(self.page_size)
        }

        fn alloc(&mut self, slot: usize, tokens: usize) -> Result<()> {
            self.ensure_slot(slot)?;
            let new_pages = self.append_pages_needed(slot, tokens);
            let pages = self.alloc_pages(new_pages);
            self.pages[slot].extend_from_slice(&pages);
            self.seq_lens[slot] += tokens;
            Ok(())
        }

        fn alloc_detached_pages(&mut self, pages: usize) -> Result<Vec<u32>> {
            let pages = self.alloc_pages(pages);
            self.retained_pages.extend(pages.iter().copied());
            Ok(pages)
        }

        fn attach_pages(&mut self, slot: usize, pages: &[u32], token_count: usize) -> Result<()> {
            self.ensure_slot(slot)?;
            self.pages[slot].clear();
            self.pages[slot].extend_from_slice(pages);
            self.seq_lens[slot] = token_count;
            self.slot_epochs[slot] = self.slot_epochs[slot].saturating_add(1);
            Ok(())
        }

        fn truncate_slot(&mut self, slot: usize, new_len: usize) -> Result<()> {
            self.ensure_slot(slot)?;
            if new_len > self.seq_lens[slot] {
                bail!("cannot grow slot {slot} via truncate");
            }
            self.seq_lens[slot] = new_len;
            let keep_pages = new_len.div_ceil(self.page_size);
            self.pages[slot].truncate(keep_pages);
            self.slot_epochs[slot] = self.slot_epochs[slot].saturating_add(1);
            Ok(())
        }

        fn free_slot(&mut self, slot: usize) {
            self.pages[slot].clear();
            self.seq_lens[slot] = 0;
            self.slot_epochs[slot] = self.slot_epochs[slot].saturating_add(1);
        }

        fn migrate(&mut self, slot: usize, start: usize, len: usize) -> Result<()> {
            self.ensure_slot(slot)?;
            let target = start.saturating_add(len);
            if target > self.seq_lens[slot] {
                self.alloc(slot, target - self.seq_lens[slot])?;
            }
            Ok(())
        }

        fn retained_count(&self) -> usize {
            self.retained_pages.len()
        }

        fn release_pages(&mut self, pages: &[u32]) {
            for page in pages {
                self.retained_pages.remove(page);
            }
        }

        fn retain_pages(&mut self, pages: &[u32]) {
            self.retained_pages.extend(pages.iter().copied());
        }
    }

    #[derive(Debug, Clone)]
    pub(super) struct MockInflight {
        output: StepOutput,
        return_not_ready_once: bool,
    }

    #[derive(Debug, Clone)]
    pub(super) struct MockExecutor {
        not_ready_once_per_submit: bool,
    }

    impl MockExecutor {
        pub(super) fn ready() -> Self {
            Self {
                not_ready_once_per_submit: false,
            }
        }

        pub(super) fn not_ready_once() -> Self {
            Self {
                not_ready_once_per_submit: true,
            }
        }
    }

    impl BackendExecutor for MockExecutor {
        type Inflight = MockInflight;

        fn submit(&mut self, plan: &ForwardPlan, _kv: &mut dyn KvPool) -> Result<Self::Inflight> {
            let mut tokens = Vec::new();
            for row in &plan.prefill_rows {
                let token = row.tokens.last().copied().map_or(1, |last| last + 1);
                tokens.push(SlotToken {
                    slot: row.slot,
                    token,
                    logprob: None,
                    finish: None,
                });
            }
            for row in &plan.decode_rows {
                tokens.push(SlotToken {
                    slot: row.slot,
                    token: row.last_token + 1,
                    logprob: None,
                    finish: None,
                });
            }
            Ok(MockInflight {
                output: StepOutput { tokens },
                return_not_ready_once: self.not_ready_once_per_submit,
            })
        }

        fn poll(&mut self, mut inflight: Self::Inflight) -> Result<PollResult<Self::Inflight>> {
            if inflight.return_not_ready_once {
                inflight.return_not_ready_once = false;
                Ok(PollResult::NotReady(inflight))
            } else {
                Ok(PollResult::Ready(inflight.output))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use infer_plan::FinishReason;

    use super::testing::{MockExecutor, MockKvPool};
    use super::*;

    #[test]
    fn test_single_request_decodes_to_max_tokens() -> Result<()> {
        let mut engine = Engine::new(MockExecutor::ready(), MockKvPool::new(1), 1);
        let handle = engine.submit_request(vec![10], 3);

        engine.run_to_idle()?;

        let completed = engine.completed(handle).expect("request completed");
        assert_eq!(completed.generated_tokens, vec![11, 12, 13]);
        assert!(matches!(completed.finish, Some(FinishReason::Length)));
        assert!(engine.is_idle());
        Ok(())
    }

    #[test]
    fn test_two_requests_interleave() -> Result<()> {
        let mut engine = Engine::new(MockExecutor::ready(), MockKvPool::new(2), 2);
        let left = engine.submit_request(vec![10], 3);
        let right = engine.submit_request(vec![100], 2);

        engine.run_to_idle()?;

        let left = engine.completed(left).expect("left request completed");
        let right = engine.completed(right).expect("right request completed");
        assert_eq!(left.generated_tokens, vec![11, 12, 13]);
        assert_eq!(right.generated_tokens, vec![101, 102]);
        assert!(matches!(left.finish, Some(FinishReason::Length)));
        assert!(matches!(right.finish, Some(FinishReason::Length)));
        Ok(())
    }

    #[test]
    fn test_overlap_not_ready_then_ready() -> Result<()> {
        let mut engine = Engine::new(MockExecutor::not_ready_once(), MockKvPool::new(1), 1);
        let handle = engine.submit_request(vec![5], 2);

        engine.step()?;
        assert!(engine.has_inflight());
        assert_eq!(engine.active_count(), 1);

        engine.step()?;
        assert!(engine.has_inflight());
        assert!(engine.completed(handle).is_none());

        engine.run_to_idle()?;

        let completed = engine.completed(handle).expect("request completed");
        assert_eq!(completed.generated_tokens, vec![6, 7]);
        assert!(matches!(completed.finish, Some(FinishReason::Length)));
        Ok(())
    }

    #[test]
    fn test_idle_plan_when_no_work() -> Result<()> {
        let mut engine = Engine::new(MockExecutor::ready(), MockKvPool::new(1), 1);

        engine.step()?;

        assert!(engine.is_idle());
        assert!(!engine.has_inflight());
        assert_eq!(engine.active_count(), 0);
        assert_eq!(engine.waiting_count(), 0);
        Ok(())
    }
}
