//! The quality court of last resort for dense-tier formats: teacher-forced
//! negative log-likelihood, the currency perplexity is quoted in.
//!
//! The greedy probes answered "does the output change" (a coarse bit) and
//! "how far do logits drift" (format-relative). NLL answers the question the
//! plan left open since S5: what does W4A16 quantization cost in *modeling*
//! terms. Every format scores the SAME token sequences (teacher-forced), so
//! the ΔNLL column is exactly the quantization price — no free-running
//! divergence, no prefix mismatch.
//!
//! Corpus: sequences greedily generated by the FIRST (baseline) format from
//! diverse prompts. Self-generated text scores low absolute NLL by
//! construction — the cross-format DELTA is the signal, and it slightly
//! FAVORS the baseline (the sequence sits in its argmax groove), making the
//! reported delta an upper bound on the candidate's disadvantage. Stated
//! here so nobody reads the absolute column as a corpus perplexity.
//!
//! ```text
//! ARLE_QWEN4_PPL=bf16,q4k cargo test -p infer-vulkan --features vulkan \
//!     --release --test qwen4_ppl -- --test-threads=1 --nocapture
//! ```
#![cfg(feature = "vulkan")]

use std::collections::BTreeMap;
use std::path::PathBuf;

use infer_gguf::safetensors::SafeTensorsDir;
use infer_vulkan::model_qwen4_exp::{Qwen4ExpDeviceMode, VulkanQwen4ExpModel};
use infer_vulkan::qwen4_config::Qwen4ExpConfig;
use vulkan_sys::VulkanContext;

const CKPT_ENV: &str = "ARLE_QWEN4_CKPT";
const CKPT_DEFAULT: &str = r"C:\Users\Asus\models\qwen3.8-flash-next-nvfp4";

fn checkpoint_dir() -> Option<PathBuf> {
    let dir = PathBuf::from(std::env::var(CKPT_ENV).unwrap_or_else(|_| CKPT_DEFAULT.into()));
    if dir.is_dir() {
        Some(dir)
    } else {
        eprintln!("SKIP: checkpoint {} not present", dir.display());
        None
    }
}

fn vocab(dir: &std::path::Path) -> BTreeMap<String, u32> {
    let src = std::fs::read_to_string(dir.join("tokenizer.json")).expect("tokenizer.json");
    let doc = infer_vulkan::qwen4_config::json::parse(&src).expect("parse tokenizer.json");
    let v = doc
        .get("model")
        .and_then(|m| m.get("vocab"))
        .and_then(|v| v.as_object())
        .expect("model.vocab");
    v.iter()
        .filter_map(|(k, id)| {
            id.as_i64()
                .and_then(|v| u32::try_from(v).ok())
                .map(|i| (k.clone(), i))
        })
        .collect()
}

/// log_softmax(logits)[target], numerically stable.
fn token_logprob(logits: &[f32], target: u32) -> f64 {
    let max = logits.iter().copied().fold(f32::NEG_INFINITY, f32::max);
    let lse: f64 = logits
        .iter()
        .map(|&v| f64::from(v - max).exp())
        .sum::<f64>()
        .ln()
        + f64::from(max);
    f64::from(logits[target as usize]) - lse
}

#[test]
fn dense_format_teacher_forced_nll() {
    let Ok(formats) = std::env::var("ARLE_QWEN4_PPL") else {
        eprintln!("SKIP: set ARLE_QWEN4_PPL=bf16,q4k[,q8] (first entry generates the corpus)");
        return;
    };
    let formats: Vec<String> = formats.split(',').map(|s| s.trim().to_string()).collect();
    assert!(formats.len() >= 2, "need a baseline and a candidate");
    let Some(dir) = checkpoint_dir() else { return };
    let ctx = match VulkanContext::create() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("SKIP: no Vulkan device ({e})");
            return;
        }
    };
    let by_tok = vocab(&dir);
    let prompt_specs: [&[&str]; 3] = [
        &["The", "Ġhistory", "Ġof", "Ġthe", "ĠRoman", "ĠEmpire"],
        &["def", "Ġfib", "(", "n", ")", ":"],
        &[
            "The",
            "Ġmost",
            "Ġimportant",
            "Ġidea",
            "Ġin",
            "Ġphysics",
            "Ġis",
        ],
    ];
    let mut prompts: Vec<Vec<u32>> = Vec::new();
    for spec in prompt_specs {
        if let Some(ids) = spec
            .iter()
            .map(|p| by_tok.get(*p).copied())
            .collect::<Option<Vec<u32>>>()
        {
            prompts.push(ids);
        } else {
            eprintln!("  (prompt dropped, missing piece: {spec:?})");
        }
    }
    assert!(prompts.len() >= 2, "not enough prompts survived the vocab");
    const GEN: usize = 96;

    // Pass 1 (baseline): greedy-extend each prompt to fix the corpus.
    // Pass 2..n: teacher-forced NLL of the SAME sequences.
    let mut corpus: Vec<Vec<u32>> = Vec::new();
    let mut table: Vec<(String, f64, usize, f64)> = Vec::new(); // (fmt, nll_sum, count, load_s)
    for (fi, fmt) in formats.iter().enumerate() {
        // SAFETY: single-threaded test binary; read once per load.
        unsafe { std::env::set_var("ARLE_QWEN4_DENSE", fmt) };
        let st = SafeTensorsDir::open_dir(&dir).expect("open checkpoint");
        let cfg = Qwen4ExpConfig::from_model_dir(&dir).expect("config");
        let t0 = std::time::Instant::now();
        let mut model =
            VulkanQwen4ExpModel::load(Some(&ctx), &st, cfg, &Qwen4ExpDeviceMode::HybridExperts)
                .expect("load");
        let load_s = t0.elapsed().as_secs_f64();
        let mut nll_sum = 0.0f64;
        let mut count = 0usize;
        for (pi, prompt) in prompts.iter().enumerate() {
            let full: Vec<u32> = if fi == 0 {
                let mut seq = prompt.clone();
                for pos in 0..prompt.len() + GEN - 1 {
                    let logits = model
                        .forward_token(0, 0, seq[pos], pos)
                        .expect("baseline forward");
                    if pos + 1 >= prompt.len() && seq.len() < prompt.len() + GEN {
                        let arg = logits
                            .iter()
                            .enumerate()
                            .max_by(|a, b| a.1.total_cmp(b.1))
                            .map(|(i, _)| i as u32)
                            .unwrap();
                        seq.push(arg);
                    }
                }
                corpus.push(seq.clone());
                seq
            } else {
                corpus[pi].clone()
            };
            // Teacher-forced: feed full[pos], score full[pos+1] from the
            // prompt boundary on (the generated region only — every format
            // scores the identical positions).
            // Reset state for the scoring pass.
            // Score only the generated region; the scoring pass below starts
            // at pos 0 with start_pos 0, which resets the recurrent state —
            // so the baseline's generation pass above does not leak into its
            // own scoring, and every format runs the identical code.
            let score_from = prompt.len() - 1;
            let mut nll_here = 0.0f64;
            for pos in 0..full.len() - 1 {
                let logits = model
                    .forward_token(0, 0, full[pos], pos)
                    .expect("scoring forward");
                if pos >= score_from {
                    nll_here -= token_logprob(&logits, full[pos + 1]);
                    count += 1;
                }
            }
            nll_sum += nll_here;
            // Reset between prompts.
            model.forward_token(0, 0, full[0], 0).expect("reset");
        }
        eprintln!(
            "[{fmt}] load {load_s:.1}s, scored {count} positions, mean NLL {:.5}",
            nll_sum / count as f64
        );
        table.push((fmt.clone(), nll_sum, count, load_s));
    }

    let base_nll = table[0].1 / table[0].2 as f64;
    eprintln!("\n── teacher-forced NLL vs {} ──", table[0].0);
    eprintln!(
        "  {:<6} {:>10} {:>10} {:>12} {:>9}",
        "format", "mean NLL", "ΔNLL", "PPL ratio", "load s"
    );
    for (fmt, sum, count, load_s) in &table {
        let nll = sum / *count as f64;
        eprintln!(
            "  {:<6} {:>10.5} {:>+10.5} {:>12.4} {:>9.1}",
            fmt,
            nll,
            nll - base_nll,
            (nll - base_nll).exp(),
            load_s
        );
    }
    eprintln!(
        "\nPPL ratio = exp(ΔNLL): 1.00x is lossless; the corpus favors the\n\
         baseline (its own greedy text), so candidate deltas are upper bounds."
    );
}
